export enum ActionTypes {
	FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
	FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING',
	FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR',
	SET_SEARCH_INPUT = 'SET_SEARCH_INPUT',
	SET_SEARCH_FILTER = 'SET_SEARCH_FILTER',
	SHOW_CURRENT_MOVIE = 'SHOW_CURRENT_MOVIE',
	HIDE_CURRENT_MOVIE = 'SHOW_CURRENT_MOVIE',
	SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE',
	REMOVE_CURRENT_MOVIE = 'REMOVE_CURRENT_MOVIE'
}

export enum SessionStorageKeys {
	LAST_SEARCH = 'LAST_SEARCH'
}
